apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: [CERTIFICATE_AUTHORITY_DATA_BASE64_ENCODED]
    server: [CLUSTER_CONTROL_PLANE_URL]
  name: [CLUSTER_NAME]

users:
- name: [CLUSTER_NAME]-admin
  user:
    as-user-extra: {}
    token: [JWT_TOKEN_BASE64_ENCODED]

contexts:
- context:
    cluster: [CLUSTER_NAME]
    namespace: [NAMESPACE]
    user: [CLUSTER_NAME]-admin
  name: [CLUSTER_NAME]-ctx

current-context: [CLUSTER_NAME]-ctx
